package signing

import (
	"encoding/hex"
	"testing"

	"github.com/ethereum/go-ethereum/common"
)

// Values below were generated by the official Python SDK's msgpack.packb and
// sign_multi_sig_action for the same envelope. They protect the exact nested
// action bytes, not merely the final digest.
func TestMultiSigEnvelopeActionBytesMatchOfficialPythonSDK(t *testing.T) {
	const nonce = uint64(1_700_000_000_123)
	envelope := MultiSigEnvelopeAction{
		SignatureChainID: "0x66eee",
		Signatures:       []CompactSignature{{R: "0x1", S: "0x2", V: 27}},
		Payload: MultiSigPayload{
			MultiSigUser: "0x1111111111111111111111111111111111111111",
			OuterSigner:  "0x14791697260e4c9a71f18484c9f997b308e59325",
			Action:       NoopAction{},
		},
	}
	components, err := L1ActionComponents(multiSigEnvelopeBody(envelope), nonce, nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	const wantAction = "83b07369676e6174757265436861696e4964a730783636656565aa7369676e6174757265739183a172a3307831a173a3307832a1761ba77061796c6f616483ac6d756c746953696755736572d92a307831313131313131313131313131313131313131313131313131313131313131313131313131313131ab6f757465725369676e6572d92a307831343739313639373236306534633961373166313834383463396639393762333038653539333235a6616374696f6e81a474797065a46e6f6f70"
	const wantConnectionID = "ae34ecfc6707091b44c8c3f1f33c8f60b9e8893177b891fb86da4b13888e4daf"
	if got := hex.EncodeToString(components.ActionBytes); got != wantAction {
		t.Fatalf("action bytes = %s, want %s", got, wantAction)
	}
	if got := hex.EncodeToString(components.ConnectionID[:]); got != wantConnectionID {
		t.Fatalf("connection ID = %s, want %s", got, wantConnectionID)
	}
	if _, err := ComputeMultiSigL1PayloadDigest(NoopAction{}, common.HexToAddress(envelope.Payload.MultiSigUser), common.HexToAddress(envelope.Payload.OuterSigner), nonce, nil, nil, true); err != nil {
		t.Fatalf("canonical L1 action rejected: %v", err)
	}
}
