package signing_test

import (
	"context"
	"encoding/hex"
	"testing"

	"github.com/Apexllcc/hyperliquid-go-sdk/signer"
	"github.com/Apexllcc/hyperliquid-go-sdk/signing"
	"github.com/ethereum/go-ethereum/common"
)

// Values were generated with Hyperliquid's official Python SDK
// sign_usd_transfer_action for the exact action below.
func TestUSDSendUserActionVectorMatchesOfficialPythonSDK(t *testing.T) {
	t.Parallel()
	action := signing.USDSendAction{
		Destination: common.HexToAddress("0x1111111111111111111111111111111111111111"),
		Amount:      "12.34",
		Time:        1700000000000,
	}
	digest, err := signing.ComputeUserActionDigest(action, true)
	if err != nil {
		t.Fatal(err)
	}
	if got := hex.EncodeToString(digest[:]); got != "f9ea9d9fc48d0d20a1d9bdb6a5ebe3c04f3d096acbd93ccd1bd8d12c4ce37c1c" {
		t.Fatalf("digest = %s", got)
	}
	local, err := signer.NewLocalPrivateKeySignerFromHex("0123456789012345678901234567890123456789012345678901234567890123")
	if err != nil {
		t.Fatal(err)
	}
	signature, err := local.SignDigest(context.Background(), digest)
	if err != nil {
		t.Fatal(err)
	}
	if got := hex.EncodeToString(signature.R[:]); got != "6fbeec23561352b9330bd3a528b81b04fe63b6d20830db247227882f6abd1546" {
		t.Fatalf("R = %s", got)
	}
	if got := hex.EncodeToString(signature.S[:]); got != "17cc062219a2cf2ba17cca386300e2f8707bca3bc9376984900a3f5faf3e9efc" {
		t.Fatalf("S = %s", got)
	}
	if signature.V != 1 {
		t.Fatalf("V = %d", signature.V)
	}
	if err := signer.Verify(digest, signature, local.Address()); err != nil {
		t.Fatalf("recover signer address: %v", err)
	}
}

// These mainnet and testnet fixtures were generated by the official Python
// SDK's sign_spot_transfer_action, sign_agent, and sign_approve_builder_fee.
func TestAdditionalUserActionVectorsMatchOfficialPythonSDK(t *testing.T) {
	t.Parallel()
	name := "bot"
	cases := []struct {
		name, digest, r, s string
		v                  uint8
		action             signing.UserSignedAction
		isMainnet          bool
	}{
		{"spot send testnet", "90b213d63cd446bcf2084359969bf6b77a1b13d75caafe53e93b1cd20139afd8", "cfda26e4e3f68280b992317178409212506dad063fc7fd7432b9802f651f3c8a", "5571968c40a5582f1e93db72ca0a781b263d8df4cc5eeb2935c1e2f08567e229", 0, signing.SpotSendAction{Destination: common.HexToAddress("0x1111111111111111111111111111111111111111"), Token: "PURR:0xc4bf3f870c0e9465323c0b6ed28096c2", Amount: "0.01", Time: 1700000000001}, false},
		{"approve agent mainnet", "2e6607cd632d6eed1548b311c4b6f2130ce806944ecee4f0c0ff20679ff1520a", "a57b417cecdcf3811762b6105b6f3066738abfe6a443644e7288b27ee8d4b143", "18e79d9ed7a684429f996c0751eeef8eec9c2905b8975ec01cd62bc6fbbc48a7", 0, signing.ApproveAgentAction{AgentAddress: common.HexToAddress("0x2222222222222222222222222222222222222222"), AgentName: &name, Nonce: 1700000000002}, true},
		{"approve builder testnet", "63a35eb9c1811dc458f363f7b4af280d5e03c43a1c22ec5e8b1ae583242ab1d3", "c389f8cce94006024a59013c62a3cce1c539c708f851a1052a8063c04b816cec", "21dd8a45859d99f2e089a5c44547b1b50e02a6c5197567b482fa398dc66a9a67", 1, signing.ApproveBuilderFeeAction{Builder: common.HexToAddress("0x2222222222222222222222222222222222222222"), MaxFeeRate: "0.001%", Nonce: 1700000000003}, false},
	}
	local, err := signer.NewLocalPrivateKeySignerFromHex("0123456789012345678901234567890123456789012345678901234567890123")
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			digest, err := signing.ComputeUserActionDigest(tc.action, tc.isMainnet)
			if err != nil {
				t.Fatal(err)
			}
			if got := hex.EncodeToString(digest[:]); got != tc.digest {
				t.Fatalf("digest=%s", got)
			}
			signature, err := local.SignDigest(context.Background(), digest)
			if err != nil {
				t.Fatal(err)
			}
			if got := hex.EncodeToString(signature.R[:]); got != tc.r {
				t.Fatalf("R=%s", got)
			}
			if got := hex.EncodeToString(signature.S[:]); got != tc.s {
				t.Fatalf("S=%s", got)
			}
			if signature.V != tc.v {
				t.Fatalf("V=%d", signature.V)
			}
			if err := signer.Verify(digest, signature, local.Address()); err != nil {
				t.Fatalf("recover signer address: %v", err)
			}
		})
	}
}
